security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
spring:
  application:
    name: spring-boot-jdbc-test
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring-boot-jdbc-test?useSSL=false
#    username: user 
#    password: dbpass

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
