security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
spring:
  application:
    name: spring-boot-jdbc-test

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true   